const express = require('express');
const nodemailer = require('nodemailer');

require('dotenv').config();

const app = express();
const port = 3000; // Change to your desired port number

// Middleware to parse JSON bodies
app.use(express.json());

// GET endpoint for testing
app.get('/webhook', async (req, res) => {
  console.log('GET request received');
  res.status(200).send("GET Reached");
});

// POST endpoint to handle webhook and send email
app.post('/webhook', async (req, res) => {
  console.log('POST request received');
  try {
    // Log the incoming request body
    const payload = req.body;
    console.log('Request Payload:', payload);

    // Validate payload
    if (!payload.title || !payload.message) {
      console.log('Invalid payload:', payload);
      return res.status(400).send('Invalid payload');
    }

    // Modify the title by removing content inside parentheses
    let title = payload.title.replace(/\(.*\)/, '').trim();
    
    // Extract the message part from the payload
    let message = payload.message;
    
    // Remove annotations from the message
    message = message.split('Annotations:')[0]; // Exclude everything after "Annotations:"

    console.log('Filtered message:', message);

    // Remove C=1 from the Value line
    message = message.replace(/C=\d+, /, ''); // Remove C=1, 

    // Make Messages_behind and its value bold
    message = message.replace(/(Messages_behind=\d+)/g, '<strong>$1</strong>');

    // Send an email with the filtered title and message
    await sendEmail(title, message);

    // Respond to the client
    res.status(200).send('Alert email sent successfully');
  } catch (error) {
    console.error('Error sending email:', error);
    res.status(500).send('Error sending email');
  }
});

// Function to send an email
async function sendEmail(title, message) {
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  // Add bold styling to values and labels
  message = message.replace(/Value:/g, '<strong>Value:</strong>')
                   .replace(/Labels:/g, '<strong>Labels:</strong>')
                   .replace(/ - /g, '<strong> - </strong>'); // Add bold to label list

  // Add a custom footer at the end
  const footer = `<br><br><strong><em>This Alert is Generated By Software Factory Team</em></strong>`;

  const mailOptions = {
    from: process.env.EMAIL_FROM,
    to: [process.env.EMAIL_TO, process.env.EMAIL_TO_1].join(', '), // Only EMAIL_TO and EMAIL_TO_1
    subject: `${title}`, // Remove 'Alert:' prefix here
    html: `<p><strong>Title:</strong> <b>${title}</b></p>
           <p><strong>Message:</strong></p>
           <pre style="white-space: pre-wrap;">${message}</pre>
           ${footer}`, // Adding the footer to the email
  };

  await transporter.sendMail(mailOptions);
  console.log('Email sent successfully to EMAIL_TO and EMAIL_TO_1');
}

// Start the server
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
